### PR TITLE
allow scrolling in the scriptcontainer to allow more scripts addition

### PR DESCRIPTION
**Pull request by smartekIT**
This will separate the scriptcontainer area section with it's own nice scrolling bar. it allow the addition of endless scripts and provide better view and control over the scripts. 

Screenshot 2023-05-14 131207

### CODE REVIEW

**Comment by Shananiganeer** [comment]
Your PR shouldn't include the modifications to config.json/readme.md that point to your fork of the plugin.

Also, you left an unclosed div in user.handlebars. You need to add "str += '</div>'" after the forEach and move "document.getElementById('scriptContainer').innerHTML = str;" to after that. That call probably shouldn't have been part of the forEach to begin with to avoid unnecessary DOM manipulation.

**Comment by smartekIT** [comment]
> Your PR shouldn't include the modifications to config.json/readme.md that point to your fork of the plugin.
> 
> Also, you left an unclosed div in user.handlebars. You need to add `str += '</div>';` after the forEach and move `document.getElementById('scriptContainer').innerHTML = str;` to after that. That call probably shouldn't have been part of the forEach to begin with to avoid unnecessary DOM manipulation.

so sorry I didn't know that. when no one answered my pr for long time, I just changed these settings so can be in beta so my meshcentral server can detect it as a higher version and pull the update for me. That's all.
Regarding the <code>str += '</div>';</code> the original line was the same at that part referring to line number 470-471 in the file. otherwise please point me to the line number you are referring to. Thanks heaps for your help.

**Comment by Shananiganeer** [comment]
On line 460 you added `str = '<div style="display: block;overflow-y: auto;max-height: 700px;">'`. That div is never closed and then str gets set as the innerHTML of scriptContainer. To have proper HTML, that tag needs to be closed. Add `str += '</div>';` on line 475 and then move `document.getElementById('scriptContainer').innerHTML = str;` from line 473 to 476.

**Comment by Shananiganeer** [comment]
The issue is with the HTML that you have generated. You open a `<div>` tag and never close it with `</div>`. To have proper HTML, that tag needs to be closed. Add str += '</div>'; on line 475 and then move document.getElementById('scriptContainer').innerHTML = str; from line 473 to 476.

The innerHTML should not have been set in the forEach loop to begin with as it manipulates the DOM for each item being added to the list as opposed to once at the end. This is a mistake in the original code, but becomes more obvious when you try to wrap the entire block in a new div.

**Comment by smartekIT** [comment]
Thanks, I tried it on my live server with your instructions and it worked. even though it gave me the same result as if I just do:
```
str += '<div style="display: block;overflow-y: auto;max-height: 700px;">';
```
so based on your instructions:
reverted the line 460 to:
```
str += '<div style="display: block;overflow-y: auto;max-height: 700px;">'
```
then added the following at line 475:
```
str += '</div>';
```
moved the following code from line 473 to 476:
```
document.getElementById('scriptContainer').innerHTML = str;
```
so now the whole function looks like the following:
```
function redrawScriptTree() {
  var lastpath = null;
  var str = '';
  var indent = 0;
  var folder_id = null;
  str += '<div style="display: block;overflow-y: auto;max-height: 700px;">'
  scriptTree.forEach(function(f) {
    if (f.path != lastpath && f.type == 'folder') {
      indent = (f.path.match(/\//g) || []).length + 1;
      var name = f.path.match(/[^\/]+$/);
      folder_id = f._id;
      str += '<div draggable="true" x-data-path="' + f.path + '" x-data-id="' + f._id + '" x-data-folder="' + folder_id + '" style="margin-left: ' + indent + 'em;" class="lifolder" onclick="toggleCollapse(this);"><span class="fname">' + name + '</span></div>';
      lastpath = f.path;
      indent += 1;
    }
    if (f.type != 'folder') {
        str += '<div id="' + f._id + '" draggable="true"  x-data-path="' + f.path + '" x-data-id="' + f._id + '" x-data-folder="' + folder_id + '" style="margin-left: ' + indent + 'em;" class="liscript" onclick="goScript(this);"><span class="fname">' + f.name + '</span> [<span class="ftype">' + f.filetype + '</span>]</div>';
    }

  });
  str += '</div>';
  document.getElementById('scriptContainer').innerHTML = str;
  var liScripts = document.querySelectorAll('.liscript');
  var liFolders = document.querySelectorAll('.lifolder');
  liScripts.forEach(function(el) {
    el.addEventListener('mousedown', function() { elementDragged = true; });
    el.addEventListener('mouseup', function() { elementDragged = false; });
    el.addEventListener('dragstart', function(evt) { evt.dataTransfer.setData('text/plain', evt.target.getAttribute('x-data-id')); });
  });
  liFolders.forEach(function(el) {
    el.addEventListener('drop', dropMove);
    el.addEventListener('dragover', function(e) { e.preventDefault(); });
    el.addEventListener('mousedown', function() { elementDragged = true; });
    el.addEventListener('mouseup', function() { elementDragged = false; });
    el.addEventListener('dragstart', function(evt) { evt.dataTransfer.setData('text/plain', evt.target.getAttribute('x-data-id')); });
  });
  resizeIframe();
  selectPreviouslySelectedScript();
}
```

you are the expert, so waiting for the confirmation?

**Comment by Shananiganeer** [comment]
Yea that's what I was talking about. Now we just need ryanblenis to come back and start maintaining this repo again.

**Comment by smartekIT** [comment]
> Yea that's what I was talking about. Now we just need ryanblenis to come back and start maintaining this repo again.

done. created a new pull request for the changes #43 
Thanks for your help mate. Also I need to thank @yourh3ro for #35 which makes life easy

**Pull request closed without merging**
